name: cpk
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.1.1
  - matplotlib=3.10.0
  - numpy=2.2.2
  - pandas=2.2.3
  - pip=25.0.1
  - polars=1.22.0
  - pytest=8.3.4
  - python=3.13.1
  - pytorch=2.5.1
  - rdkit=2024.09.5
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - sympy=1.13.3
  - tqdm=4.67.1
  - pip:
      - neattime==0.0.4
      - pykan==0.2.8
