name: chem_phys_kans
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.1.1
  - matplotlib=3.9.2
  - numpy=2.1.1
  - pandas=2.2.2
  - pip=24.2
  - pytest=8.3.3
  - python=3.12.6
  - pytorch=2.4.0
  - rdkit=2024.03.5
  - scikit-learn=1.5.2
  - seaborn=0.13.2
  - sympy=1.13.3
  - tqdm=4.66.5
  - pip:
      - pykan==0.2.6